Issue #22: Should not activate under Cloud Next.
acquia/memcache-settings pull request #23
Opened 2022-07-07 16:48 UTC by janusman

Code is fine under Cloud Classic, however it does not under Cloud Next. Examples: acquia_hosting_site_info doesn't exist on ACN, the Memcache binary protocol and compression are both disallowed on ACN, etc. 

Since the platform already auto-includes similar (but correctly-working code), this change makes this code not do anything.

2022-07-07 17:31 UTC, janusman commented
Tests fail, but not because of the code changes...

2022-08-01 17:01 UTC, danepowell requested changes
As mentioned in the readme, this project just copies the publicly available docs: https://github.com/acquia/memcache-settings#acquia-memcache-settings

Any changes need to be merged into the DOCS first to ensure technical review

2022-08-01 17:01 UTC, danepowell commented on memcache.settings.php
> + * Last change: 07/07/2022
> Tests fail, but not because of the code changes...

Not sure why you'd say that, the error is due to this line not meeting code standards.

> ERROR | Doc comment short description must end with a full
ERROR | Doc comment short description must be on a single line,

https://github.com/acquia/memcache-settings/runs/7238600302?check_suite_focus=true#step:8:53

2022-08-01 17:31 UTC, danepowell commented
I'm proposing a new process to maintain this file in DOC-25063, but until that's agreed upon we should stick to the old process, which is to get this merged into the DOCS repo first.

2022-08-02 22:22 UTC, danepowell approved these changes

2022-08-02 22:26 UTC, merged